<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Отменить',
    'Create' => 'Создать',
    'Created' => 'Создано',
    'Creating' => 'Создание',
    'Details of the' => 'Детали',
    'Edit' => 'Редактировать',
    'Editing' => 'Редактирование',
    'Save' => 'Сохранить',
    'Slug' => '',
    'Updated' => 'Обновлено',
    'Active' => 'Активно',
    'Add widget' => 'Добавить виджет',
    'Additional parameters' => 'Дополнительные параметры',
    'Available widgets' => 'Доступные виджеты',
    'Base parameters' => 'Основные параметры',
    'Can be deleted' => 'Может быть удалено',
    'Code' => 'Код',
    'Copy' => 'Копировать',
    'Existing text pages' => 'Существующие текстовые страницы',
    'External link' => 'Внешняя ссылка',
    'Functional pages' => 'Функциональные страницы',
    'Has menu image' => 'Есть картинка в меню',
    'Has settings' => 'Есть настройки',
    'Has submenu' => 'Есть подменю',
    'Internal link' => 'Внутренняя ссылка',
    'Layout' => 'Шаблон',
    'Link to settings' => 'Ссылка на настройки',
    'Main page' => 'Главная страница',
    'Manage menus' => 'Управление меню',
    'Menu' => 'Меню',
    'Menu image' => 'Картинка меню',
    'Menu not found' => 'Меню не найдено',
    'Name' => 'Название',
    'No available widgets for selected block' => 'Нет доступных виджетов для выбранного блока',
    'Open in new tab' => 'Открывать в новой вкладке',
    'Page templates' => 'Шаблоны страниц',
    'Pages' => 'Страницы',
    'Pages without menu' => 'Страницы без меню',
    'Position' => 'Позиция',
    'Reset' => 'Сбросить',
    'Saved' => 'Сохранено',
    'Search' => 'Поиск',
    'Single per page' => 'Один на страницу',
    'Sorter' => 'Порядок',
    'Template' => 'Шаблон',
    'Template widgets' => 'Виджеты шаблона',
    'Templates' => 'Шаблоны',
    'Text' => 'Текст',
    'Text page' => 'Текстовая страница',
    'Type' => 'Тип',
    'Widget class' => 'Класс виджета',
    'Widget options' => 'Опции виджета',
    'external link' => 'внешняя ссылка',
    'external link for' => 'внешняя ссылка для',
    'internal link' => 'внутренняя ссылка',
    'internal link for' => 'внутренняя ссылка для',
    'menu' => 'меню',
    'template' => 'шаблон',
    'template widget' => 'виджет шаблона',
    'text page' => 'текстовой страницы',
    'text page for' => 'текстовой страницы для',
];
