<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Add widget' => '',
    'Additional parameters' => '',
    'Available widgets' => '',
    'Base parameters' => '',
    'Can be deleted' => '',
    'Code' => '',
    'Copy' => '',
    'Existing text pages' => '',
    'External link' => '',
    'Functional pages' => '',
    'Has menu image' => '',
    'Has settings' => '',
    'Has submenu' => '',
    'Internal link' => '',
    'Layout' => '',
    'Link to settings' => '',
    'Main page' => '',
    'Manage menus' => '',
    'Menu' => '',
    'Menu image' => '',
    'Menu not found' => '',
    'Name' => '',
    'No available widgets for selected block' => '',
    'Open in new tab' => '',
    'Pages' => '',
    'Position' => '',
    'Reset' => '',
    'Search' => '',
    'Single per page' => '',
    'Slug' => '',
    'Sorter' => '',
    'Template' => '',
    'Template widgets' => '',
    'Templates' => '',
    'Text' => '',
    'Text page' => '',
    'Type' => '',
    'Widget class' => '',
    'Widget options' => '',
    'Without menu' => '',
    'external link' => '',
    'external link for' => '',
    'internal link' => '',
    'internal link for' => '',
    'menu' => '',
    'template' => '',
    'template widget' => '',
    'text page' => '',
    'text page for' => '',
];
